FROM ros:humble

SHELL ["/bin/bash", "-lc"]

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3-colcon-common-extensions \
    ros-humble-xacro \
    ros-humble-cv-bridge \
    ros-humble-ackermann-msgs \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-joint-state-broadcaster \
    ros-humble-ackermann-steering-controller \
    ros-humble-ros-gz-sim \
    ros-humble-ros-gz-bridge \
  && rm -rf /var/lib/apt/lists/*
